import sqlite3
import pandas as pd

DB_FILE = "network_security.db"


def init_db():
    """Initializes the database and creates the required tables."""
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()

    # Table for raw aggregated network traffic flows
    cursor.execute('''
                   CREATE TABLE IF NOT EXISTS network_flows
                   (
                       id
                       INTEGER
                       PRIMARY
                       KEY
                       AUTOINCREMENT,
                       timestamp
                       TEXT,
                       src_ip
                       TEXT,
                       dst_ip
                       TEXT,
                       protocol
                       INTEGER,
                       pkt_count
                       INTEGER,
                       byte_count
                       INTEGER,
                       avg_pkt_size
                       REAL
                   )
                   ''')

    # Table for security alerts generated by the ML model
    cursor.execute('''
                   CREATE TABLE IF NOT EXISTS alerts
                   (
                       id
                       INTEGER
                       PRIMARY
                       KEY
                       AUTOINCREMENT,
                       timestamp
                       TEXT,
                       src_ip
                       TEXT,
                       dst_ip
                       TEXT,
                       protocol
                       INTEGER,
                       pkt_count
                       INTEGER,
                       byte_count
                       INTEGER,
                       avg_pkt_size
                       REAL,
                       anomaly_score
                       REAL
                   )
                   ''')

    conn.commit()
    conn.close()


def log_flow(timestamp, src_ip, dst_ip, proto, pkt_count, byte_count, avg_pkt_size):
    """Inserts a captured flow record into the database."""
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute('''
                   INSERT INTO network_flows (timestamp, src_ip, dst_ip, protocol, pkt_count, byte_count, avg_pkt_size)
                   VALUES (?, ?, ?, ?, ?, ?, ?)
                   ''', (timestamp, src_ip, dst_ip, proto, pkt_count, byte_count, avg_pkt_size))
    conn.commit()
    conn.close()


def log_alert(timestamp, src_ip, dst_ip, proto, pkt_count, byte_count, avg_pkt_size, score):
    """Inserts an anomaly alert record into the database."""
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute('''
                   INSERT INTO alerts (timestamp, src_ip, dst_ip, protocol, pkt_count, byte_count, avg_pkt_size,
                                       anomaly_score)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                   ''', (timestamp, src_ip, dst_ip, proto, pkt_count, byte_count, avg_pkt_size, score))
    conn.commit()
    conn.close()


def get_recent_flows(limit=100):
    """Fetches the latest flows as a Pandas DataFrame."""
    conn = sqlite3.connect(DB_FILE)
    df = pd.read_sql_query(f"SELECT * FROM network_flows ORDER BY id DESC LIMIT {limit}", conn)
    conn.close()
    return df


def get_alerts(limit=50):
    """Fetches the latest anomaly alerts as a Pandas DataFrame."""
    conn = sqlite3.connect(DB_FILE)
    df = pd.read_sql_query(f"SELECT * FROM alerts ORDER BY id DESC LIMIT {limit}", conn)
    conn.close()
    return df


if __name__ == "__main__":
    init_db()
    print("[*] Database initialized successfully.")

